apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-privileged-scc
subjects:
- kind: ServiceAccount
  name: pipeline
roleRef:
  kind: ClusterRole
  name: "system:openshift:scc:privileged"
  apiGroup: rbac.authorization.k8s.io
