apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: s2i-nodejs
  namespace: demo-builds
spec:
  source:
    type: Git
    git:
      url: https://github.com/sclorg/nodejs-ex
  strategy:
    name: source-to-image
    kind: ClusterBuildStrategy
  paramValues:
  - name: builder-image
    value: image-registry.openshift-image-registry.svc:5000/openshift/nodejs:16-ubi9
  output:
    image: image-registry.openshift-image-registry.svc:5000/demo-builds/nodejs-ex:s2i
