apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: buildah-nodejs
  namespace: demo-builds
spec:
  source:
    type: Git
    git:
      url: https://github.com/shipwright-io/sample-nodejs.git
    contextDir: docker-build
  strategy:
    name: buildah
    kind: ClusterBuildStrategy
  output:
    image: image-registry.openshift-image-registry.svc:5000/demo-builds/nodejs-ex:buildah
